# Generated by Django 4.0.2 on 2022-03-12 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Places',
            new_name='Workplace',
        ),
        migrations.AlterModelOptions(
            name='workplace',
            options={'verbose_name': 'Workplace', 'verbose_name_plural': 'Workplaces'},
        ),
    ]
