# Generated by Django 4.0.2 on 2022-03-12 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0003_offices'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingRooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('desc', models.CharField(max_length=250, verbose_name='Desc')),
                ('free', models.BooleanField(verbose_name='Free')),
            ],
            options={
                'verbose_name': 'MeetingRoom',
                'verbose_name_plural': 'MeetingRooms',
            },
        ),
    ]
