# Generated by Django 4.0.2 on 2022-03-17 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0005_workplacebooking_officebooking_meetingroomsbooking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingroomsbooking',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='officebooking',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='workplacebooking',
            name='date',
            field=models.DateField(),
        ),
    ]
