# Generated by Django 4.0.2 on 2022-03-17 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0006_alter_meetingroomsbooking_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingrooms',
            name='desc',
            field=models.TextField(max_length=250, verbose_name='Desc'),
        ),
        migrations.AlterField(
            model_name='offices',
            name='desc',
            field=models.TextField(max_length=250, verbose_name='Desc'),
        ),
        migrations.AlterField(
            model_name='workplace',
            name='desc',
            field=models.TextField(max_length=250, verbose_name='Desc'),
        ),
    ]
