# Generated by Django 4.0.2 on 2022-03-17 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0007_alter_meetingrooms_desc_alter_offices_desc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingroomsbooking',
            name='email',
            field=models.EmailField(default='', max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='officebooking',
            name='email',
            field=models.EmailField(default='', max_length=254, verbose_name='Email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workplacebooking',
            name='email',
            field=models.EmailField(default=' ', max_length=254, verbose_name='Email'),
        ),
    ]
