# Generated by Django 3.0 on 2022-05-16 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pricing', '0010_auto_20220516_1738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalmeetingroomsbooking',
            name='people',
        ),
        migrations.RemoveField(
            model_name='historicalofficebooking',
            name='people',
        ),
        migrations.RemoveField(
            model_name='historicalworkplacebooking',
            name='people',
        ),
        migrations.RemoveField(
            model_name='meetingroomsbooking',
            name='people',
        ),
        migrations.RemoveField(
            model_name='officebooking',
            name='people',
        ),
        migrations.RemoveField(
            model_name='workplacebooking',
            name='people',
        ),
        migrations.AddField(
            model_name='historicalmeetingroomsbooking',
            name='user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalofficebooking',
            name='user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalworkplacebooking',
            name='user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='meetingroomsbooking',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='officebooking',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workplacebooking',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
