# Generated by Django 3.2 on 2022-07-01 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0011_auto_20220630_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalplacebooking',
            name='user',
            field=models.CharField(max_length=100, verbose_name='Username'),
        ),
        migrations.AlterField(
            model_name='placebooking',
            name='user',
            field=models.CharField(max_length=100, verbose_name='Username'),
        ),
    ]
