# Generated by Django 3.2 on 2022-07-02 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0013_comments_historicalcomments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='historicalcomments',
            name='comment',
        ),
        migrations.AddField(
            model_name='comments',
            name='text',
            field=models.TextField(default=1, max_length=250, verbose_name='Text'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalcomments',
            name='text',
            field=models.TextField(default='1', max_length=250, verbose_name='Text'),
            preserve_default=False,
        ),
    ]
