# Generated by Django 3.2 on 2022-07-02 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0014_auto_20220702_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='user_id',
            field=models.CharField(default='Guest', max_length=50, verbose_name='User_id'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='username',
            field=models.CharField(default='Guest', max_length=50, verbose_name='Username'),
        ),
        migrations.AlterField(
            model_name='historicalcomments',
            name='user_id',
            field=models.CharField(default='Guest', max_length=50, verbose_name='User_id'),
        ),
        migrations.AlterField(
            model_name='historicalcomments',
            name='username',
            field=models.CharField(default='Guest', max_length=50, verbose_name='Username'),
        ),
    ]
