# Generated by Django 3.2 on 2022-07-03 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0015_auto_20220702_2116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalplacebooking',
            old_name='user',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='placebooking',
            old_name='user',
            new_name='username',
        ),
    ]
