# Generated by Django 3.2 on 2022-07-03 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0016_auto_20220703_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalplacebooking',
            name='_in',
            field=models.DateTimeField(help_text='When the cow got back IN FROM Pasture.', null=True),
        ),
        migrations.AddField(
            model_name='historicalplacebooking',
            name='out',
            field=models.DateTimeField(help_text='When the cow went OUT TO Pasture.', null=True),
        ),
        migrations.AddField(
            model_name='placebooking',
            name='_in',
            field=models.DateTimeField(help_text='When the cow got back IN FROM Pasture.', null=True),
        ),
        migrations.AddField(
            model_name='placebooking',
            name='out',
            field=models.DateTimeField(help_text='When the cow went OUT TO Pasture.', null=True),
        ),
    ]
