# Generated by Django 3.2 on 2022-07-03 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0017_auto_20220703_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalplacebooking',
            name='_in',
            field=models.DateField(help_text='When the booking ends.', null=True),
        ),
        migrations.AlterField(
            model_name='historicalplacebooking',
            name='out',
            field=models.DateField(help_text='When the booking starts.', null=True),
        ),
        migrations.AlterField(
            model_name='placebooking',
            name='_in',
            field=models.DateField(help_text='When the booking ends.', null=True),
        ),
        migrations.AlterField(
            model_name='placebooking',
            name='out',
            field=models.DateField(help_text='When the booking starts.', null=True),
        ),
    ]
